### ISSUE TITLE
称号被默认频道覆盖

### ISSUE THREAD

**Issue by fishcpy** [handy-git/PlayerChat#5]

**Comment by handy-git** [comment]
加变量

**Comment by fishcpy** [comment]
怎么加

**Comment by handy-git** [comment]
仅供参考

```yaml
# 展示物品
item:
  # 是否开启
  enable: true
  # 需求内容
  format: '[i]'
  # 内容格式
  content: '&5[&a展示了一个 &6${item} &a点击查看&5]'

# 聊天管理 渠道可无限根据下面格式添加
chat:
  # 默认渠道(严禁删除本渠道)
  default:
    # 是否开启
    enable: true
    name: 默认频道
    # 聊天格式 支持变量
    format:
      # 聊天前缀
      prefix:
        text: '[%ip2region_provincial%]%playerTitle_use%'
        hover:
        - '&8▪ &6称号数量: %playerTitle_number%'
        - '&8▪ &6称号币数量: %playerTitle_coin%'
      # 聊天玩家名
      player:
        text: '&f%player_name%&7: '
        hover:
        - '&8▪ &6所在世界: %multiverse_world_alias%'
        - '&8▪ &6所属公会: %playerGuild_name%'
        - '&8▪ &6任务币: %playerTask_coin%'
        - '&8▪ &6精英币: %elitemobs_player_money%'
        - '&8▪ &6精英等级: %elitemobs_player_active_guild_rank_name%'
        - '&8▪ &6战斗等级:  %elitemobs_player_combat_tier%'
      # 聊天内容
      msg:
        text: '&f'
        hover:
        - '&7时间: %server_time_h:mm:ss a%'
  # 扩展渠道一
  PlayerGuild:
    # 是否开启
    enable: true
    name: '&7[&a公会频道&7]'
    # 聊天格式 支持变量
    format:
      # 聊天前缀
      prefix:
        text: ${channel}%playerGuild_show_name%
        hover:
        - xxx公会信息
      # 聊天玩家名
      player:
        text: '&f%player_name%&7: '
        hover:
        - '&8▪ &6当前渠道: ${channel}'
      # 聊天内容
      msg:
        text: '&f'
        hover:
        - '&7时间: %server_time_h:mm:ss a%'
at:
  # 是否开启
  enable: true
  # 音效列表 https://bukkit.windit.net/javadoc/org/bukkit/Sound.html
  sound: BLOCK_ANVIL_LAND
```
